config/routes.rb
Rails.application.routes.draw do
  resources :term_search_logs
  resources :parts_of_speeches
  resources :terms do
    collection do 
      get :search
      post :search_word
    end 
  end

  resources :dictionaries
  resources :irs_codes
  resources :legals

  root to: "terms#index"
  #mount ActionCable.server => "/cable"

  #root 'dashboard#index'
  root 'admin/dashboard#index'
  get  'admin/dashboard/new_tab'

  get '/login', to: 'static_pages#home'

  # route for logged in user
  get 'profile' => 'users#edit'
  patch 'update_profile' => 'users#update'
  get 'auth/:provider/callback' => 'sessions#create'
  post 'auth/:provider/callback' => 'sessions#create'
  get 'auth/failure' => 'sessions#failure'
  get 'signout' => 'sessions#destroy', as: 'signout'

end

app/models/term.rb
class Term < ApplicationRecord
  acts_as_tree
  belongs_to :dictionary
  #validates_uniqueness_of :name, scope: :dictionary, allow: nil
  belongs_to :parts_of_speech
  
  has_many :term_search_logs  # 
  has_many :users, through: :term_search_logs

#=begin 
  searchable do
    text :name
    text :definition
    integer :parent_id
    integer :dictionary_id
  end  
#=end
  
end

app/controllers/admin/term_controller.rb
class Admin::TermController < ApplicationController
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_action :set_term, only: [:show, :edit, :update, :destroy]
  skip_before_action :set_term, only: [:search, :search_word]

  # GET /terms
  # GET /terms.json
  def index
    #@terms = Term.all.paginate(:page => params[:page])
    @terms = [] 
  end
  
  def search_word 
  #  if term = Term.find(params[:q])
  #    redirect_to :show, id: term
  #  end
    redirect_to action: :show, id: params[:q]
  end   
    
  
=begin  
    if @term = Term.find(params[:q])
      @found_terms = Term.where(name: @term.name).includes(:dictionary).order('dictionaries.position')
    end
    @term.users << current_user 
    render :show
=end
    
 # end

  # GET /terms/1
  # GET /terms/1.json
  def show
   if @term   
      @found_terms = Term.where(name: @term.name).includes(:dictionary).order('dictionaries.position')
    end
    @term.users << current_user
  end

  # GET /terms/new
  def new
    @term = Term.new
  end

  # GET /terms/1/edit
  def edit
  end

  # POST /terms
  # POST /terms.json
  def create
    @term = Term.new(term_params)

    respond_to do |format|
      if @term.save
        format.html { redirect_to @term, notice: 'Term was successfully created.' }
        format.json { render :show, status: :created, location: @term }
      else
        format.html { render :new }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /terms/1
  # PATCH/PUT /terms/1.json
  def update
    respond_to do |format|
      if @term.update(term_params)
        format.html { redirect_to @term, notice: 'Term was successfully updated.' }
        format.json { render :show, status: :ok, location: @term }
      else
        format.html { render :edit }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terms/1
  # DELETE /terms/1.json
  def destroy
    @term.destroy
    respond_to do |format|
      format.html { redirect_to terms_url, notice: 'Term was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  #.first.terms.limit(1).order("RANDOM()")
  def search
    if q = params[:q]
      search_dictionary_ids = params[:search_dictionary_ids].present? \
        ? params[:search_dictionary_ids] : [3]
      
      r = Term.search do 
        fulltext q  do
          boost_fields name: 2.0
          phrase_fields definition: 2.0
        end
        #order_by :position, :asc
        with :dictionary_id, search_dictionary_ids  if search_dictionary_ids.present?
      end
      @results = r.results
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_term
      @term = Term.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def term_params
      params.require(:term).permit(:name, :definition, :parent_id, :dictionary_id, :position)
    end
end

app/helpers/admin/term_helper.rb
module Admin::TermHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/terms/_dict_term.html.slim
.col-md-4
  .well.well-lg
    h2 = dict_term.dictionary.abbreviation
    / h3 = dict_term.name
    = dict_term.definition

    p    
    .row

        = link_to 'Warn', edit_term_path(dict_term), :class => "btn btn-warning"

        = link_to 'Make Note', edit_term_path(dict_term), :class => "btn btn-success"

        = link_to 'Danger!', edit_term_path(dict_term), :class => "btn btn-danger"
        = link_to 'Edit', edit_term_path(dict_term), :class => "btn btn-info"
    

app/views/terms/_form.html.slim
= semantic_bootstrap_nested_form_for @term do |f|
  /
    - if @term.errors.any?
      #error_explanation
        h2 = "#{pluralize(@term.errors.count, "error")} prohibited this term from being saved:"
          ul
            - @term.errors.full_messages.each do |message|
              li = message

  = f.input :dictionary, :input_html => { :disabled => true } 
  = f.inputs  :name, :definition
  
  = f.actions do 
    = f.action :submit, :as => :button 
    = f.action :cancel, :as => :link
  

app/views/terms/_search_form.html.slim
= semantic_bootstrap_nested_form_for :search,  url: search_word_terms_path, id: 'search_terms', method: :post do |f|
  .row
    .col-md-3
    .col-md-5
      = render 'select2_form', f: f
    .col-md-1 
      = f.actions do
        = f.action :submit, as: :button, label: 'Search', button_html: {class: "btn btn-success btn-lg pull-left"}
 
    .col-md-3 
  .row
    .col-md-4
    .col-md-4     
    .col-md-3
      #select_dictionary   
        = f.input :dictionary_ids, as: :select, multiple: true, \
          label: 'Using Dictionaries',
          hint: 'default is search all', collection: Dictionary.all.pluck(:name, :id)
        

javascript:
  $("#search_dictionary_ids").select2({
    theme: "bootstrap",
  });

app/views/terms/_select2_form.html.slim
/ = form_tag(search_terms_path, method: :post, remote: true)

= select_tag "q", [], style: "width: 90%", id: 'query_terms', \
  data: { placeholder: "Search definitions" }
  
  / = f.input :query_terms, as: :select, multiple: false, data: { placeholder: "Search definitions" }

javascript:

  function formatRepo(repo) {
    console.log('--------format repo------------');
    console.log(repo);
    if (repo.loading) return repo.text;

    var markup = "<div class='select2-result-repository clearfix'>" +
      "<div class='select2-result-repository__meta__NOT'>" +
        "<div class='select2-result-repository__title'>" + (repo.field_label || repo.text) + "<span class='select2-result-repository__description'>: " + repo.definition + "</span> <span class='select2-result-repository__source'>" + repo.source_name  + "</span></div>";

    /*  

    var markup = "<div class='select2-result-repository clearfix'>" +
      "<div class='select2-result-repository__meta__NOT'>" +
        "<div class='select2-result-repository__title'>" + (repo.field_label || repo.text)  +  ": source:" +   + " </div>";
    
  

      if (repo.field_note) {
        markup += "<div class='select2-result-repository__description'>" + repo.field_note + "</div>";
      }

      if (repo.field_instructions) {
        markup += "<div class='select2-result-repository__description'>" + repo.field_instructions + "</div>";
      }

      markup += "<div class='select2-result-repository__statistics'>" +
        "<div class='select2-result-repository__forks'><i class='fa fa-flash'></i> " + " Source:</div>" +
        "<div class='select2-result-repository__stargazers'><i class='fa fa-star'></i> " + repo.source_name  + " " + repo.udf_explorer_link + "</div>" +
        "</div>" +
        "</div></div>";
    */

    return markup;
  }
    
  function formatRepoSelection(repo) {
    console.log('called formatRepoSelection');
    return (repo.field_label || repo.text);
  }
  
  $("#query_terms").select2({
    theme: "bootstrap",
    // tags: true,
    allowClear: true,
    ajax: {
      url: "#{search_terms_path}",
      dataType: 'json',
      delay: 250,
      data: function (params) {
        var dict_ids = $("#search_dictionary_ids").val();
        console.log("Dict ids: " + dict_ids);
        return {
          q: params.term, // search term
          search_dictionary_ids: dict_ids,
          page: params.page
        };
      },
      processResults: function (data, params) {
        // parse the results into the format expected by Select2
        // since we are using custom formatting functions we do not need to
        // alter the remote JSON data, except to indicate that infinite
        // scrolling can be used
        params.page = params.page || 1;

        return {
          results: data.items,
          pagination: {
            more: (params.page * 30) < data.total_count
          }
        };
      },
      cache: true
    },
    escapeMarkup: function (markup) { return markup; }, // let our custom formatter work
    minimumInputLength: 1,
    templateResult: formatRepo, // omitted for brevity, see the source of this page
    templateSelection: formatRepoSelection // omitted for brevity, see the source of this page
  });
  

  
  



  

app/views/terms/edit.html.slim
h1 Editing term

== render 'form'

= link_to 'Show', @term
'|
= link_to 'Back', terms_path

app/views/terms/index.html.slim
= render 'search_form'

/
  h1 Listing terms

  table.table.table-highlight
    thead
      tr
        th Name
        th Definition

        th
        th
        th

    tbody
      - @terms.each do |term|
        tr
          td = term.name
          td = term.definition
          td = link_to 'Show', term
          td = link_to 'Edit', edit_term_path(term)
          td = link_to 'Destroy', term, data: {:confirm => 'Are you sure?'}, :method => :delete

  = will_paginate @terms
  br
  = link_to 'New Term', new_term_path

app/views/terms/new.html.slim
h1 New term

== render 'form'

= link_to 'Back', terms_path

app/views/terms/show.html.slim
= render 'search_form'

p#notice = notice

h1.bg-info = @term.name

/

  p
    strong Definition:
    = @term.definition
  p
    strong Parent:
    = @term.parent_id
  p
    strong Dictionary:
    = @term.dictionary
  p
    strong Position:
    = @term.position
    
    
  
- @found_terms.in_groups_of(3) do |terms|
  .row
    = render partial: 'dict_term', collection: terms.compact
   
    

= link_to 'Edit', edit_term_path(@term)
'|
= link_to 'Back', terms_path