config/routes.rb
Rails.application.routes.draw do
  resources :term_search_logs
  resources :parts_of_speeches
  resources :terms do
    collection do 
      get :search
      post :search_word
    end 
  end

  resources :dictionaries
  resources :irs_codes
  resources :legals

  root to: "terms#index"
  #mount ActionCable.server => "/cable"

  #root 'dashboard#index'
  root 'admin/dashboard#index'
  get  'admin/dashboard/new_tab'

  get '/login', to: 'static_pages#home'

  # route for logged in user
  get 'profile' => 'users#edit'
  patch 'update_profile' => 'users#update'
  get 'auth/:provider/callback' => 'sessions#create'
  post 'auth/:provider/callback' => 'sessions#create'
  get 'auth/failure' => 'sessions#failure'
  get 'signout' => 'sessions#destroy', as: 'signout'

end

app/models/dictionary.rb
class Dictionary < ApplicationRecord
  has_many :terms
  validates_uniqueness_of :name
  
  has_one :logo, as: :attachable, class_name: 'Attachment'
  accepts_nested_attributes_for :logo
end

app/controllers/admin/dictionary_controller.rb
class Admin::DictionaryController < ApplicationController
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  before_action :set_dictionary, only: [:show, :edit, :update, :destroy]

  # GET /dictionaries
  # GET /dictionaries.json
  def index
    @dictionaries = Dictionary.all
  end

  # GET /dictionaries/1
  # GET /dictionaries/1.json
  def show
  end

  # GET /dictionaries/new
  def new
    @dictionary = Dictionary.new
  end

  # GET /dictionaries/1/edit
  def edit
  end

  # POST /dictionaries
  # POST /dictionaries.json
  def create
    @dictionary = Dictionary.new(dictionary_params)

    respond_to do |format|
      if @dictionary.save
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully created.' }
        format.json { render :show, status: :created, location: @dictionary }
      else
        format.html { render :new }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dictionaries/1
  # PATCH/PUT /dictionaries/1.json
  def update
    respond_to do |format|
      if @dictionary.update(dictionary_params)
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully updated.' }
        format.json { render :show, status: :ok, location: @dictionary }
      else
        format.html { render :edit }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dictionaries/1
  # DELETE /dictionaries/1.json
  def destroy
    @dictionary.destroy
    respond_to do |format|
      format.html { redirect_to dictionaries_url, notice: 'Dictionary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dictionary
      @dictionary = Dictionary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dictionary_params
    #params.require(:dictionary).permit!
    params.require(:dictionary).permit(:name, :description, :edition, :position, :abbreviation, logo_attributes: [:asset])
    end
end

app/helpers/admin/dictionary_helper.rb
module Admin::DictionaryHelper
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/views/dictionaries/_form.html.slim
= semantic_bootstrap_nested_form_for  @dictionary, html: { multipart: true } do |f|
  - if @dictionary.errors.any?
    #error_explanation
      h2 = "#{pluralize(@dictionary.errors.count, "error")} prohibited this dictionary from being saved:"
      ul
        - @dictionary.errors.full_messages.each do |message|
          li = message

  = f.inputs :name, :description, :edition, :abbreviation
  / 
    = f.input :logo, as: :file   
    = f.semantic_fields_for :logo do |attachment_f| 
      = attachment_f.input :asset

  = f.actions  
    
  
  

app/views/dictionaries/edit.html.slim
h1 Editing dictionary

== render 'form'

= link_to 'Show', @dictionary
'|
= link_to 'Back', dictionaries_path

app/views/dictionaries/index.html.slim
h1 Listing dictionaries

table
  thead
    tr
      th Name
      th Description
      th Edition
      th Abbreviation
      th
      th
      th

  tbody
    - @dictionaries.each do |dictionary|
      tr
        td = dictionary.name
        td = dictionary.description
        td = dictionary.edition
        td = dictionary.abbreviation
        td = link_to 'Show', dictionary
        td = link_to 'Edit', edit_dictionary_path(dictionary)
        td = link_to 'Destroy', dictionary, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Dictionary', new_dictionary_path

app/views/dictionaries/new.html.slim
h1 New dictionary

== render 'form'

= link_to 'Back', dictionaries_path

app/views/dictionaries/show.html.slim
p#notice = notice

.well.well-sm
  h2 = @dictionary.name
  = @dictionary.description

p  
  strong Abbreviation:
  = @dictionary.abbreviation

p  
  strong Description:
  = @dictionary.description
p
  strong Edition:
  = @dictionary.edition
p
  strong Position:
  = @dictionary.position


- if @dictionary.try(:logo)
  p
    strong Logo:
    - @dictionary.logo.asset.styles.keys.each do |s| 
      = image_tag @dictionary.logo.asset.url(s)
      = s.to_s
    
= link_to 'Edit', edit_dictionary_path(@dictionary)
'|
= link_to 'Back', dictionaries_path