config/routes.rb
Rails.application.routes.draw do
  resources :term_search_logs
  resources :parts_of_speeches
  resources :terms do
    collection do 
      get :search
      post :search_word
    end 
  end

  resources :dictionaries
  resources :irs_codes
  resources :legals

  root to: "terms#index"
  #mount ActionCable.server => "/cable"

  #root 'dashboard#index'
  root 'admin/dashboard#index'
  get  'admin/dashboard/new_tab'

  get '/login', to: 'static_pages#home'

  # route for logged in user
  get 'profile' => 'users#edit'
  patch 'update_profile' => 'users#update'
  get 'auth/:provider/callback' => 'sessions#create'
  post 'auth/:provider/callback' => 'sessions#create'
  get 'auth/failure' => 'sessions#failure'
  get 'signout' => 'sessions#destroy', as: 'signout'

end

app/models/legal.rb
class Legal < ActiveRecord::Base
  acts_as_tree order: "title"
end

app/controllers/legals_controller.rb
class LegalsController < ApplicationController
  before_action :set_legal, only: [:show, :edit, :update, :destroy]

  # GET /legals
  # GET /legals.json
  def index
    @legals = Legal.all
  end

  # GET /legals/1
  # GET /legals/1.json
  def show
  end

  # GET /legals/new
  def new
    @legal = Legal.new
  end

  # GET /legals/1/edit
  def edit
  end

  # POST /legals
  # POST /legals.json
  def create
    @legal = Legal.new(legal_params)

    respond_to do |format|
      if @legal.save
        format.html { redirect_to @legal, notice: 'Legal was successfully created.' }
        format.json { render :show, status: :created, location: @legal }
      else
        format.html { render :new }
        format.json { render json: @legal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /legals/1
  # PATCH/PUT /legals/1.json
  def update
    respond_to do |format|
      if @legal.update(legal_params)
        format.html { redirect_to @legal, notice: 'Legal was successfully updated.' }
        format.json { render :show, status: :ok, location: @legal }
      else
        format.html { render :edit }
        format.json { render json: @legal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legals/1
  # DELETE /legals/1.json
  def destroy
    @legal.destroy
    respond_to do |format|
      format.html { redirect_to legals_url, notice: 'Legal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_legal
      @legal = Legal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def legal_params
      params.require(:legal).permit(:title, :body, :parent_id, :source)
    end
end

app/helpers/legals_helper.rb
module LegalsHelper
end

app/views/legals/_form.html.slim
= form_for @legal do |f|
  - if @legal.errors.any?
    #error_explanation
      h2 = "#{pluralize(@legal.errors.count, "error")} prohibited this legal from being saved:"
      ul
        - @legal.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :parent_id
    = f.number_field :parent_id
  .field
    = f.label :source
    = f.text_field :source
  .actions = f.submit

app/views/legals/edit.html.slim
h1 Editing legal

== render 'form'

= link_to 'Show', @legal
'|
= link_to 'Back', legals_path

app/views/legals/index.html.slim
h1 Listing legals

table
  thead
    tr
      th Title
      th Body
      th Parent
      th Source
      th
      th
      th

  tbody
    - @legals.each do |legal|
      tr
        td = legal.title
        td = legal.body
        td = legal.parent_id
        td = legal.source
        td = link_to 'Show', legal
        td = link_to 'Edit', edit_legal_path(legal)
        td = link_to 'Destroy', legal, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Legal', new_legal_path

app/views/legals/new.html.slim
h1 New legal

== render 'form'

= link_to 'Back', legals_path

app/views/legals/show.html.slim
p#notice = notice

p
  strong Title:
  = @legal.title
p
  strong Body:
  = @legal.body
p
  strong Parent:
  = @legal.parent_id
p
  strong Source:
  = @legal.source

= link_to 'Edit', edit_legal_path(@legal)
'|
= link_to 'Back', legals_path