config/routes.rb
Rails.application.routes.draw do
  resources :term_search_logs
  resources :parts_of_speeches
  resources :terms do
    collection do 
      get :search
      post :search_word
    end 
  end

  resources :dictionaries
  resources :irs_codes
  resources :legals

  root to: "terms#index"
  #mount ActionCable.server => "/cable"

  #root 'dashboard#index'
  root 'admin/dashboard#index'
  get  'admin/dashboard/new_tab'

  get '/login', to: 'static_pages#home'

  # route for logged in user
  get 'profile' => 'users#edit'
  patch 'update_profile' => 'users#update'
  get 'auth/:provider/callback' => 'sessions#create'
  post 'auth/:provider/callback' => 'sessions#create'
  get 'auth/failure' => 'sessions#failure'
  get 'signout' => 'sessions#destroy', as: 'signout'

end

app/models/parts_of_speech.rb
class PartsOfSpeech < ApplicationRecord
end

app/controllers/parts_of_speeches_controller.rb
class PartsOfSpeechesController < ApplicationController
  before_action :set_parts_of_speech, only: [:show, :edit, :update, :destroy]

  # GET /parts_of_speeches
  # GET /parts_of_speeches.json
  def index
    @parts_of_speeches = PartsOfSpeech.all
  end

  # GET /parts_of_speeches/1
  # GET /parts_of_speeches/1.json
  def show
  end

  # GET /parts_of_speeches/new
  def new
    @parts_of_speech = PartsOfSpeech.new
  end

  # GET /parts_of_speeches/1/edit
  def edit
  end

  # POST /parts_of_speeches
  # POST /parts_of_speeches.json
  def create
    @parts_of_speech = PartsOfSpeech.new(parts_of_speech_params)

    respond_to do |format|
      if @parts_of_speech.save
        format.html { redirect_to @parts_of_speech, notice: 'Parts of speech was successfully created.' }
        format.json { render :show, status: :created, location: @parts_of_speech }
      else
        format.html { render :new }
        format.json { render json: @parts_of_speech.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts_of_speeches/1
  # PATCH/PUT /parts_of_speeches/1.json
  def update
    respond_to do |format|
      if @parts_of_speech.update(parts_of_speech_params)
        format.html { redirect_to @parts_of_speech, notice: 'Parts of speech was successfully updated.' }
        format.json { render :show, status: :ok, location: @parts_of_speech }
      else
        format.html { render :edit }
        format.json { render json: @parts_of_speech.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts_of_speeches/1
  # DELETE /parts_of_speeches/1.json
  def destroy
    @parts_of_speech.destroy
    respond_to do |format|
      format.html { redirect_to parts_of_speeches_url, notice: 'Parts of speech was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parts_of_speech
      @parts_of_speech = PartsOfSpeech.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parts_of_speech_params
      params.require(:parts_of_speech).permit(:name, :abbreviation, :description)
    end
end

app/helpers/parts_of_speeches_helper.rb
module PartsOfSpeechesHelper
end

app/views/parts_of_speeches/_form.html.slim
= form_for @parts_of_speech do |f|
  - if @parts_of_speech.errors.any?
    #error_explanation
      h2 = "#{pluralize(@parts_of_speech.errors.count, "error")} prohibited this parts_of_speech from being saved:"
      ul
        - @parts_of_speech.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :abbreviation
    = f.text_field :abbreviation
  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit

app/views/parts_of_speeches/edit.html.slim
h1 Editing parts_of_speech

== render 'form'

= link_to 'Show', @parts_of_speech
'|
= link_to 'Back', parts_of_speeches_path

app/views/parts_of_speeches/index.html.slim
h1 Listing parts_of_speeches

table
  thead
    tr
      th Name
      th Abbreviation
      th Description
      th
      th
      th

  tbody
    - @parts_of_speeches.each do |parts_of_speech|
      tr
        td = parts_of_speech.name
        td = parts_of_speech.abbreviation
        td = parts_of_speech.description
        td = link_to 'Show', parts_of_speech
        td = link_to 'Edit', edit_parts_of_speech_path(parts_of_speech)
        td = link_to 'Destroy', parts_of_speech, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Parts of speech', new_parts_of_speech_path

app/views/parts_of_speeches/new.html.slim
h1 New parts_of_speech

== render 'form'

= link_to 'Back', parts_of_speeches_path

app/views/parts_of_speeches/show.html.slim
p#notice = notice

p
  strong Name:
  = @parts_of_speech.name
p
  strong Abbreviation:
  = @parts_of_speech.abbreviation
p
  strong Description:
  = @parts_of_speech.description

= link_to 'Edit', edit_parts_of_speech_path(@parts_of_speech)
'|
= link_to 'Back', parts_of_speeches_path